### PR TITLE
`tslib` follow-up: bump TypeScript version

### PR DESCRIPTION
**Pull request by bencmbrook**
## Related Issues

- Investigating https://transcend.height.app/T-20982

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Review by MadDataScience — APPROVED** [review]

**Review by eligrey — APPROVED** [review]
Haven't tested this myself but this lgtm. I can do some testing later today/tomorrow

**Comment by bencmbrook** [comment]
Splitting vercel playground fix into https://github.com/transcend-io/consent-manager-ui/pull/103

**Review by eligrey — APPROVED** [review]

**Review by michaelfarrell76 — APPROVED** [review]
tested that this still works!

**Comment by bencmbrook** [comment]
@michaelfarrell76 note we may need to update the Yarn PnP SDKs as there's usually some associated update with TS versions

**Pull request merged**
