### PR TITLE
Adding bottom margin 2px on .complete-options-form

### PR DESCRIPTION
**Pull request by banzzai**
## Related Issues

- _[none]_

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Review by eligrey — COMMENTED** [review]
don't forget to bump the version in package.json

**Review by kearnie — DISMISSED** [review]
thank youuu 🫶

**Comment by banzzai** [comment]
> don't forget to bump the version in package.json

Oh yes, it's been too long... Minor version bump and that should be enough, right?

**Comment by banzzai** [comment]
Didn't bother to merge, reopening.

**Pull request closed without merging**
