### PR TITLE
Rewrite the `transcend` API handler

### PR DESCRIPTION
**Pull request by bencmbrook**
Rips out the Event dispatch architecture in favor of a simpler API. That enables much simpler two-way communication with way less code! The key insight here is that it's possible to get the JS Object out of Preact by passing a callback prop to the root `<App>` element.

## Related Issues

- Toward [T-20802](https://transcend.height.app/T-20802) Add `transcend.getViewState()` API to CM UI

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Review by eligrey — DISMISSED** [review]
lgtm. Note that you can make functions async instead of using Promise.resolve for slightly cleaner code

**Comment by bencmbrook** [comment]
> lgtm. Note that you can make functions async instead of using Promise.resolve for slightly cleaner code

I did that originally but there's an lint rule against using async w/o await. I actually kinda like Promise.resolve because it's more clear that it's intentionally returning a promise, and not an old async function that we switched to synchronous later on

**Comment by eligrey** [comment]
Sure, that's fine with me. The UI isn't exactly space constrained, so it's not a big deal to have the `Promise.resolve()` calls

**Review by eligrey — APPROVED** [review]

**Review by michaelfarrell76 — APPROVED** [review]
much cleaner!

**Pull request merged**
