### PR TITLE
Add some basic styles to playground

### PR DESCRIPTION
**Pull request by bencmbrook**
## Related Issues

- _[none]_

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Review by bencmbrook — COMMENTED** [review]
Note: I'm not sure why .pnp.cjs and .pnp.loader.mjs weren't checked in before... @michaelfarrell76 were these files not popping up for you on `yarn install`?

**Comment by michaelfarrell76** [comment]
@bencmbrook not sure why but my comp is creating a node_modules folder and throwing those out

**Comment by michaelfarrell76** [comment]
Screen Shot 2022-08-31 at 7 48 02 PM

@bencmbrook these are the node/yarn versions we are currently pinned on as a team

**Comment by bencmbrook** [comment]
Kk yeah, there's a few repo config things to do here separately (I'm on the same versions)

**Comment by michaelfarrell76** [comment]
@bencmbrook do you know what may be up? i was looking at this on the airgap.js-types repo gave up after strugling

**Review by michaelfarrell76 — APPROVED** [review]

**Comment by michaelfarrell76** [comment]
@bencmbrook i fixed it, i had a yarn.yml added somehow to my home directory

**Comment by michaelfarrell76** [comment]
hey @bencmbrook im going to comment this out because its doing some weird things in dark mode
Screen Shot 2022-08-31 at 9 42 20 PM

**Comment by bencmbrook** [comment]
Interesting. That's worth some investigation because these CSS rules shouldn't be applying to elements the shadow DOM

**Pull request merged**
